# Generated by Django 5.2.9 on 2026-02-03 12:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feepayment_academic_year_feepayment_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=core.models.get_today),
        ),
        migrations.AlterUniqueTogether(
            name='feepayment',
            unique_together={('student', 'academic_year', 'term')},
        ),
    ]
