# Generated by Django 5.2.9 on 2026-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staffsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grades',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
