# Generated by Django 5.2.9 on 2026-05-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_academicyear_results_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='first_term_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='second_term_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='third_term_visible',
            field=models.BooleanField(default=False),
        ),
    ]
