# Generated by Django 6.0.1 on 2026-08-11 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bigautofield_drift'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('closes_on', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Shown to applicants on the public admissions page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_setting', to='core.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(-3, 'Pre-Nursery'), (-2, 'Nursery 1'), (-1, 'Nursery 2'), (1, 'Primary 1'), (2, 'Primary 2'), (3, 'Primary 3'), (4, 'Primary 4'), (5, 'Primary 5'), (6, 'Primary 6'), (7, 'JSS 1'), (8, 'JSS 2'), (9, 'JSS 3'), (10, 'SS 1'), (11, 'SS 2'), (12, 'SS 3')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.admissionsetting')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('setting', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('level', models.IntegerField(choices=[(-3, 'Pre-Nursery'), (-2, 'Nursery 1'), (-1, 'Nursery 2'), (1, 'Primary 1'), (2, 'Primary 2'), (3, 'Primary 3'), (4, 'Primary 4'), (5, 'Primary 5'), (6, 'Primary 6'), (7, 'JSS 1'), (8, 'JSS 2'), (9, 'JSS 3'), (10, 'SS 1'), (11, 'SS 2'), (12, 'SS 3')])),
                ('status', models.CharField(choices=[('pending_payment', 'Awaiting Payment'), ('paid', 'Paid — Form Incomplete'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('admitted', 'Admitted'), ('waitlisted', 'Waitlisted'), ('rejected', 'Not Offered')], default='pending_payment', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tx_ref', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nationality', models.CharField(blank=True, default='Nigerian', max_length=100)),
                ('state_of_origin', models.CharField(blank=True, max_length=100)),
                ('lga', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('home_address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('genotype', models.CharField(blank=True, max_length=10)),
                ('medical_info', models.TextField(blank=True)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_class', models.CharField(blank=True, max_length=100)),
                ('reason_for_leaving', models.TextField(blank=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_occupation', models.CharField(blank=True, max_length=200)),
                ('guardian_address', models.TextField(blank=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='admissions/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.academicyear')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact_phone', 'date_of_birth'], name='core_applic_contact_fd369c_idx'), models.Index(fields=['contact_email', 'date_of_birth'], name='core_applic_contact_334f83_idx')],
            },
        ),
    ]
