# Generated by Django 5.2.17 on 2026-08-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_admissionsetting_admissionfee_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="agrees_to_school_authority",
            field=models.BooleanField(
                default=False,
                help_text="Parent/guardian agrees to raise concerns with the school authority rather than confronting staff directly or involving outside parties.",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="confirms_rules_read",
            field=models.BooleanField(
                default=False,
                help_text="Parent/guardian confirms having read and understood the school's rules.",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="father_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="application",
            name="mother_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
