# Generated by Django 6.1.1 on 2026-09-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_application_agrees_to_school_authority_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='department',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'grade', 'fee_type', 'gender', 'department')},
        ),
    ]
