# Generated by Django 5.2.17 on 2026-09-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_feestructure_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feestructure",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="student_type",
            field=models.CharField(
                choices=[("new", "New"), ("returning", "Returning")],
                default="new",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_type",
            field=models.CharField(
                choices=[("new", "New"), ("returning", "Returning")],
                default="new",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feestructure",
            unique_together={
                (
                    "academic_year",
                    "grade",
                    "fee_type",
                    "gender",
                    "department",
                    "student_type",
                )
            },
        ),
    ]
