# Generated by Django 6.1.1 on 2026-09-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_feestructure_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
