# Generated by Django 5.2.17 on 2026-09-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_feestructure_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feestructure",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="section",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Leave blank to apply to every section of this grade (A, B, C…); set to override just one section, e.g. 'A'.",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feestructure",
            unique_together={
                (
                    "academic_year",
                    "grade",
                    "section",
                    "fee_type",
                    "gender",
                    "department",
                    "student_type",
                )
            },
        ),
    ]
