# Generated by Django 5.2.17 on 2026-09-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_feestructure_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffsalary",
            name="account_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="staffsalary",
            name="account_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="staffsalary",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
