# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_staffsalary_account_name_staffsalary_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="designation",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("principal", "Principal"),
                    ("vice_principal", "Vice Principal"),
                    ("administrator", "Administrator"),
                    ("librarian", "Librarian"),
                    ("counselor", "Counselor"),
                    ("security", "Security"),
                    ("director_clubs_society", "Director Clubs & Society"),
                    ("cashier", "Cashier"),
                    ("head_teacher", "Head Teacher"),
                    ("senior_master", "Senior Master"),
                    ("health_mistress", "Health Mistress"),
                    ("exams_master", "Exams Master"),
                    ("ict_hod", "ICT HOD"),
                    ("hod_science", "HOD Science"),
                    ("barrister", "Barrister"),
                ],
                default="teacher",
                max_length=30,
            ),
        ),
    ]
