# Generated by Django 6.1.1 on 2026-09-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_staff_bank_and_current_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('administrator', 'Administrator'), ('librarian', 'Librarian'), ('counselor', 'Counselor'), ('security', 'Security'), ('director_clubs_society', 'Director Clubs & Society'), ('cashier', 'Cashier'), ('head_teacher', 'Head Teacher'), ('senior_master', 'Senior Master'), ('health_mistress', 'Health Mistress'), ('nanny', 'Nanny'), ('exams_master', 'Exams Master'), ('ict_hod', 'ICT HOD'), ('hod_science', 'HOD Science'), ('barrister', 'Barrister')], default='teacher', max_length=30),
        ),
    ]
