# Generated by Django 6.1.1 on 2026-09-21 14:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_staff_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(default=core.models.get_today),
        ),
    ]
