# Generated by Django 5.2.17 on 2026-10-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_staff_joining_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feepayment",
            name="fee_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.feestructure"
            ),
        ),
    ]
